<?php
/**
 * Created by PhpStorm.
 * User: gaozhongqiang
 * Date: 2019/6/2
 * Time: 10:06
 * 后台入口
 */
namespace app\modules;
use yii\base\Module;

class admin extends Module{
    public $controllerNamespace = 'app\modules\controllers';
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
}